// eslint.config.js - OpenVox JavaScript Linting Configuration
import js from '@eslint/js';

export default [
    js.configs.recommended,
    {
        files: ['**/*.js'],
        languageOptions: {
            ecmaVersion: 2022,
            sourceType: 'module',
            globals: {
                window: 'readonly',
                document: 'readonly',
                console: 'readonly',
                setTimeout: 'readonly',
                clearTimeout: 'readonly',
                setInterval: 'readonly',
                clearInterval: 'readonly',
                requestAnimationFrame: 'readonly',
                cancelAnimationFrame: 'readonly',
                localStorage: 'readonly',
                fetch: 'readonly',
                URL: 'readonly',
                URLSearchParams: 'readonly',
                FormData: 'readonly',
                FileReader: 'readonly',
                Audio: 'readonly',
                HTMLAudioElement: 'readonly',
                Element: 'readonly',
                HTMLElement: 'readonly',
                Event: 'readonly',
                TouchEvent: 'readonly',
                CustomEvent: 'readonly',
                MutationObserver: 'readonly',
                IntersectionObserver: 'readonly',
                ResizeObserver: 'readonly',
                CanvasRenderingContext2D: 'readonly',
                HTMLCanvasElement: 'readonly',
                SVGElement: 'readonly',
            },
        },
        rules: {
            'no-unused-vars': ['error', {
                argsIgnorePattern: '^_',
                varsIgnorePattern: '^_',
                caughtErrorsIgnorePattern: '^_',
            }],
            'no-undef': 'error',
            'no-multiple-empty-lines': ['error', { max: 1 }],
            'no-trailing-spaces': 'error',
            'semi': ['error', 'always'],
            'quotes': ['error', 'single'],
            'indent': ['error', 4],
            'comma-dangle': ['error', 'only-multiline'],
            'prefer-const': 'warn',
            'arrow-spacing': 'error',
            'block-spacing': 'error',
            'keyword-spacing': 'error',
            'space-before-blocks': 'error',
            'space-before-function-paren': ['error', {
                anonymous: 'always',
                named: 'never',
                asyncArrow: 'always',
            }],
            'no-empty': 'off',
        },
    },
    {
        ignores: ['static/js/app.js', 'e2e/**/*.js', 'playwright.config.js'],
    },
];
