/**
 * Generated by orval v8.4.1 🍺
 * Do not edit manually.
 * OpenVox API
 * OpenAPI spec version: 1.0.0
 */
import axios from 'axios';
import type {
  AxiosInstance,
  AxiosRequestConfig,
  AxiosResponse
} from 'axios';

export type PostV1AudioSpeechBody = {
  input?: string;
  response_format?: string;
  stream?: boolean;
  voice?: string;
};

export type PostApiStudioSourcesBodyOne = {
  file?: Blob;
};

export type PostApiStudioSourcesBodyTwoCleaningSettings = { [key: string]: unknown };

export type PostApiStudioSourcesBodyTwoUrlSettings = { [key: string]: unknown };

export type PostApiStudioSourcesBodyTwo = {
  cleaning_settings?: PostApiStudioSourcesBodyTwoCleaningSettings;
  git_subpath?: string;
  git_url?: string;
  text?: string;
  title?: string;
  url?: string;
  url_settings?: PostApiStudioSourcesBodyTwoUrlSettings;
};

export type PutApiStudioSourcesSourceIdBody = {
  cleaned_text?: string;
  title?: string;
};

export type PostApiStudioSourcesSourceIdCoverBody = {
  cover?: Blob;
};

export type PostApiStudioSourcesSourceIdReCleanBody = { [key: string]: unknown };

export type PutApiStudioSourcesSourceIdMoveBody = {
  folder_id?: string;
};

export type PostApiStudioEpisodesBody = {
  breathing_intensity?: string;
  chunk_max_length?: number;
  chunk_strategy?: string;
  code_block_rule?: string;
  output_format?: string;
  source_id?: string;
  title?: string;
  voice_id?: string;
};

export type PutApiStudioEpisodesEpisodeIdBody = {
  title?: string;
};

export type PostApiStudioEpisodesEpisodeIdRegenerateWithSettingsBody = {
  breathing_intensity?: string;
  chunk_max_length?: number;
  chunk_strategy?: string;
  code_block_rule?: string;
  output_format?: string;
  voice_id?: string;
};

export type PostApiStudioEpisodesBulkMoveBody = {
  episode_ids?: string[];
  folder_id?: string;
};

export type PostApiStudioEpisodesBulkDeleteBody = {
  episode_ids?: string[];
};

export type PutApiStudioEpisodesEpisodeIdMoveBody = {
  folder_id?: string;
};

export type PostApiStudioFoldersBody = {
  name?: string;
  parent_id?: string;
  sort_order?: number;
};

export type PutApiStudioFoldersFolderIdBody = {
  name?: string;
  parent_id?: string;
  sort_order?: number;
};

export type PostApiStudioReorderBody = {
  items?: string[];
};

export type PostApiStudioTagsBody = {
  name?: string;
};

export type PostApiStudioSourcesSourceIdTagsBody = {
  tag_ids?: string[];
};

export type PostApiStudioEpisodesEpisodeIdTagsBody = {
  tag_ids?: string[];
};

export type PostApiStudioPlaybackEpisodeIdBody = {
  current_chunk_index?: number;
  percent_listened?: number;
  position_secs?: number;
};

export type PutApiStudioSettingsBody = { [key: string]: unknown };

export type PostApiStudioPreviewCleanBody = {
  text?: string;
};

export type PostApiStudioPreviewContentBody = {
  subpath?: string;
  type?: string;
  url?: string;
};

export type PostApiStudioPreviewChunksBody = {
  max_chars?: number;
  strategy?: string;
  text?: string;
};

export const getOpenVoxAPI = (axiosInstance: AxiosInstance = axios) => {
/**
 * Serve OpenAPI spec for Orval client generation.
 * @summary Serve OpenAPI spec for Orval client generation.
 */
const getOpenapiJson = (
     options?: AxiosRequestConfig
 ): Promise<AxiosResponse<void>> => {
    return axiosInstance.get(
      `/openapi.json`,options
    );
  }

/**
 * Serve the web interface.
 * @summary Serve the web interface.
 */
const get = (
     options?: AxiosRequestConfig
 ): Promise<AxiosResponse<void>> => {
    return axiosInstance.get(
      `/`,options
    );
  }

/**
 * Health check endpoint for container orchestration.

    Returns service status and basic model info.
 * @summary Health check endpoint for container orchestration.
 */
const getHealth = (
     options?: AxiosRequestConfig
 ): Promise<AxiosResponse<void>> => {
    return axiosInstance.get(
      `/health`,options
    );
  }

/**
 * List available voices.

    Returns OpenAI-compatible voice list format.
 * @summary List available voices.
 */
const getV1Voices = (
     options?: AxiosRequestConfig
 ): Promise<AxiosResponse<void>> => {
    return axiosInstance.get(
      `/v1/voices`,options
    );
  }

/**
 * OpenAI-compatible speech generation endpoint.

    Request body:
        model: string (ignored, for compatibility)
        input: string (required) - Text to synthesize
        voice: string (optional) - Voice ID or path
        response_format: string (optional) - Audio format
        stream: boolean (optional) - Enable streaming

    Returns:
        Audio file or streaming audio response
 * @summary OpenAI-compatible speech generation endpoint.
 */
const postV1AudioSpeech = (
    postV1AudioSpeechBody: PostV1AudioSpeechBody, options?: AxiosRequestConfig
 ): Promise<AxiosResponse<void>> => {
    return axiosInstance.post(
      `/v1/audio/speech`,
      postV1AudioSpeechBody,options
    );
  }

/**
 * Upload file, submit URL, paste text, or import git repository.
 * @summary Upload file, submit URL, paste text, or import git
 */
const postApiStudioSources = (
    postApiStudioSourcesBody: PostApiStudioSourcesBodyOne | PostApiStudioSourcesBodyTwo, options?: AxiosRequestConfig
 ): Promise<AxiosResponse<void>> => {
    return axiosInstance.post(
      `/api/studio/sources`,
      postApiStudioSourcesBody,options
    );
  }

/**
 * List all sources.
 * @summary List all sources.
 */
const getApiStudioSources = (
     options?: AxiosRequestConfig
 ): Promise<AxiosResponse<void>> => {
    return axiosInstance.get(
      `/api/studio/sources`,options
    );
  }

/**
 * Get a source with cleaned text.
 * @summary Get a source with cleaned text.
 */
const getApiStudioSourcesSourceId = (
    sourceId: string, options?: AxiosRequestConfig
 ): Promise<AxiosResponse<void>> => {
    return axiosInstance.get(
      `/api/studio/sources/${sourceId}`,options
    );
  }

/**
 * Update source title or cleaned_text.
 * @summary Update source title or cleaned_text.
 */
const putApiStudioSourcesSourceId = (
    sourceId: string,
    putApiStudioSourcesSourceIdBody: PutApiStudioSourcesSourceIdBody, options?: AxiosRequestConfig
 ): Promise<AxiosResponse<void>> => {
    return axiosInstance.put(
      `/api/studio/sources/${sourceId}`,
      putApiStudioSourcesSourceIdBody,options
    );
  }

/**
 * Delete source and associated episodes/audio.
 * @summary Delete source and associated episodes/audio.
 */
const deleteApiStudioSourcesSourceId = (
    sourceId: string, options?: AxiosRequestConfig
 ): Promise<AxiosResponse<void>> => {
    return axiosInstance.delete(
      `/api/studio/sources/${sourceId}`,options
    );
  }

/**
 * Get cover art for a source.
 * @summary Get cover art for a source.
 */
const getApiStudioSourcesSourceIdCover = (
    sourceId: string, options?: AxiosRequestConfig
 ): Promise<AxiosResponse<void>> => {
    return axiosInstance.get(
      `/api/studio/sources/${sourceId}/cover`,options
    );
  }

/**
 * Upload cover art for a source.
 * @summary Upload cover art for a source.
 */
const postApiStudioSourcesSourceIdCover = (
    sourceId: string,
    postApiStudioSourcesSourceIdCoverBody: PostApiStudioSourcesSourceIdCoverBody, options?: AxiosRequestConfig
 ): Promise<AxiosResponse<void>> => {const formData = new FormData();
if(postApiStudioSourcesSourceIdCoverBody.cover !== undefined) {
 formData.append(`cover`, postApiStudioSourcesSourceIdCoverBody.cover);
 }

    return axiosInstance.post(
      `/api/studio/sources/${sourceId}/cover`,
      formData,options
    );
  }

/**
 * Re-run normalizer on a source with different options.
 * @summary Re-run normalizer on a source with different optio
 */
const postApiStudioSourcesSourceIdReClean = (
    sourceId: string,
    postApiStudioSourcesSourceIdReCleanBody: PostApiStudioSourcesSourceIdReCleanBody, options?: AxiosRequestConfig
 ): Promise<AxiosResponse<void>> => {
    return axiosInstance.post(
      `/api/studio/sources/${sourceId}/re-clean`,
      postApiStudioSourcesSourceIdReCleanBody,options
    );
  }

/**
 * Move a source to a folder.
 * @summary Move a source to a folder.
 */
const putApiStudioSourcesSourceIdMove = (
    sourceId: string,
    putApiStudioSourcesSourceIdMoveBody: PutApiStudioSourcesSourceIdMoveBody, options?: AxiosRequestConfig
 ): Promise<AxiosResponse<void>> => {
    return axiosInstance.put(
      `/api/studio/sources/${sourceId}/move`,
      putApiStudioSourcesSourceIdMoveBody,options
    );
  }

/**
 * Create an episode — chunk text and enqueue generation.
 * @summary Create an episode — chunk text and enqueue generat
 */
const postApiStudioEpisodes = (
    postApiStudioEpisodesBody: PostApiStudioEpisodesBody, options?: AxiosRequestConfig
 ): Promise<AxiosResponse<void>> => {
    return axiosInstance.post(
      `/api/studio/episodes`,
      postApiStudioEpisodesBody,options
    );
  }

/**
 * List all episodes.
 * @summary List all episodes.
 */
const getApiStudioEpisodes = (
     options?: AxiosRequestConfig
 ): Promise<AxiosResponse<void>> => {
    return axiosInstance.get(
      `/api/studio/episodes`,options
    );
  }

/**
 * Get episode with its chunks.
 * @summary Get episode with its chunks.
 */
const getApiStudioEpisodesEpisodeId = (
    episodeId: string, options?: AxiosRequestConfig
 ): Promise<AxiosResponse<void>> => {
    return axiosInstance.get(
      `/api/studio/episodes/${episodeId}`,options
    );
  }

/**
 * Update episode metadata.
 * @summary Update episode metadata.
 */
const putApiStudioEpisodesEpisodeId = (
    episodeId: string,
    putApiStudioEpisodesEpisodeIdBody: PutApiStudioEpisodesEpisodeIdBody, options?: AxiosRequestConfig
 ): Promise<AxiosResponse<void>> => {
    return axiosInstance.put(
      `/api/studio/episodes/${episodeId}`,
      putApiStudioEpisodesEpisodeIdBody,options
    );
  }

/**
 * Delete episode and audio files.
 * @summary Delete episode and audio files.
 */
const deleteApiStudioEpisodesEpisodeId = (
    episodeId: string, options?: AxiosRequestConfig
 ): Promise<AxiosResponse<void>> => {
    return axiosInstance.delete(
      `/api/studio/episodes/${episodeId}`,options
    );
  }

/**
 * Re-generate all chunks for an episode.
 * @summary Re-generate all chunks for an episode.
 */
const postApiStudioEpisodesEpisodeIdRegenerate = (
    episodeId: string, options?: AxiosRequestConfig
 ): Promise<AxiosResponse<void>> => {
    return axiosInstance.post(
      `/api/studio/episodes/${episodeId}/regenerate`,undefined,options
    );
  }

/**
 * Re-generate episode with new settings, with undo support.
 * @summary Re-generate episode with new settings, with undo s
 */
const postApiStudioEpisodesEpisodeIdRegenerateWithSettings = (
    episodeId: string,
    postApiStudioEpisodesEpisodeIdRegenerateWithSettingsBody: PostApiStudioEpisodesEpisodeIdRegenerateWithSettingsBody, options?: AxiosRequestConfig
 ): Promise<AxiosResponse<void>> => {
    return axiosInstance.post(
      `/api/studio/episodes/${episodeId}/regenerate-with-settings`,
      postApiStudioEpisodesEpisodeIdRegenerateWithSettingsBody,options
    );
  }

/**
 * Undo an episode regeneration within the grace period.
 * @summary Undo an episode regeneration within the grace peri
 */
const postApiStudioUndoUndoId = (
    undoId: string, options?: AxiosRequestConfig
 ): Promise<AxiosResponse<void>> => {
    return axiosInstance.post(
      `/api/studio/undo/${undoId}`,undefined,options
    );
  }

/**
 * Move multiple episodes to a folder.
 * @summary Move multiple episodes to a folder.
 */
const postApiStudioEpisodesBulkMove = (
    postApiStudioEpisodesBulkMoveBody: PostApiStudioEpisodesBulkMoveBody, options?: AxiosRequestConfig
 ): Promise<AxiosResponse<void>> => {
    return axiosInstance.post(
      `/api/studio/episodes/bulk-move`,
      postApiStudioEpisodesBulkMoveBody,options
    );
  }

/**
 * Delete multiple episodes.
 * @summary Delete multiple episodes.
 */
const postApiStudioEpisodesBulkDelete = (
    postApiStudioEpisodesBulkDeleteBody: PostApiStudioEpisodesBulkDeleteBody, options?: AxiosRequestConfig
 ): Promise<AxiosResponse<void>> => {
    return axiosInstance.post(
      `/api/studio/episodes/bulk-delete`,
      postApiStudioEpisodesBulkDeleteBody,options
    );
  }

/**
 * Regenerate a single chunk.
 * @summary Regenerate a single chunk.
 */
const postApiStudioEpisodesEpisodeIdChunksChunkIndexRegenerate = (
    episodeId: string,
    chunkIndex: number, options?: AxiosRequestConfig
 ): Promise<AxiosResponse<void>> => {
    return axiosInstance.post(
      `/api/studio/episodes/${episodeId}/chunks/${chunkIndex}/regenerate`,undefined,options
    );
  }

/**
 * Cancel a generating episode and reset error chunks to pending.
 * @summary Cancel a generating episode and reset error chunks
 */
const postApiStudioEpisodesEpisodeIdCancel = (
    episodeId: string, options?: AxiosRequestConfig
 ): Promise<AxiosResponse<void>> => {
    return axiosInstance.post(
      `/api/studio/episodes/${episodeId}/cancel`,undefined,options
    );
  }

/**
 * Retry all error chunks for an episode.
 * @summary Retry all error chunks for an episode.
 */
const postApiStudioEpisodesEpisodeIdRetryErrors = (
    episodeId: string, options?: AxiosRequestConfig
 ): Promise<AxiosResponse<void>> => {
    return axiosInstance.post(
      `/api/studio/episodes/${episodeId}/retry-errors`,undefined,options
    );
  }

/**
 * Serve a chunk's audio file.
 * @summary Serve a chunk's audio file.
 */
const getApiStudioEpisodesEpisodeIdAudioChunkIndex = (
    episodeId: string,
    chunkIndex: number, options?: AxiosRequestConfig
 ): Promise<AxiosResponse<void>> => {
    return axiosInstance.get(
      `/api/studio/episodes/${episodeId}/audio/${chunkIndex}`,options
    );
  }

/**
 * Serve merged full episode audio.
 * @summary Serve merged full episode audio.
 */
const getApiStudioEpisodesEpisodeIdAudioFull = (
    episodeId: string, options?: AxiosRequestConfig
 ): Promise<AxiosResponse<void>> => {
    return axiosInstance.get(
      `/api/studio/episodes/${episodeId}/audio/full`,options
    );
  }

/**
 * Move an episode to a folder.
 * @summary Move an episode to a folder.
 */
const putApiStudioEpisodesEpisodeIdMove = (
    episodeId: string,
    putApiStudioEpisodesEpisodeIdMoveBody: PutApiStudioEpisodesEpisodeIdMoveBody, options?: AxiosRequestConfig
 ): Promise<AxiosResponse<void>> => {
    return axiosInstance.put(
      `/api/studio/episodes/${episodeId}/move`,
      putApiStudioEpisodesEpisodeIdMoveBody,options
    );
  }

/**
 * Create a new folder.
 * @summary Create a new folder.
 */
const postApiStudioFolders = (
    postApiStudioFoldersBody: PostApiStudioFoldersBody, options?: AxiosRequestConfig
 ): Promise<AxiosResponse<void>> => {
    return axiosInstance.post(
      `/api/studio/folders`,
      postApiStudioFoldersBody,options
    );
  }

/**
 * Rename or move a folder.
 * @summary Rename or move a folder.
 */
const putApiStudioFoldersFolderId = (
    folderId: string,
    putApiStudioFoldersFolderIdBody: PutApiStudioFoldersFolderIdBody, options?: AxiosRequestConfig
 ): Promise<AxiosResponse<void>> => {
    return axiosInstance.put(
      `/api/studio/folders/${folderId}`,
      putApiStudioFoldersFolderIdBody,options
    );
  }

/**
 * Delete a folder and all its contents (episodes audio files are deleted).
 * @summary Delete a folder and all its contents (episodes aud
 */
const deleteApiStudioFoldersFolderId = (
    folderId: string, options?: AxiosRequestConfig
 ): Promise<AxiosResponse<void>> => {
    return axiosInstance.delete(
      `/api/studio/folders/${folderId}`,options
    );
  }

/**
 * Start playing all episodes in a folder as a playlist.
 * @summary Start playing all episodes in a folder as a playli
 */
const postApiStudioFoldersFolderIdPlaylist = (
    folderId: string, options?: AxiosRequestConfig
 ): Promise<AxiosResponse<void>> => {
    return axiosInstance.post(
      `/api/studio/folders/${folderId}/playlist`,undefined,options
    );
  }

/**
 * Get all episodes in a folder for playlist building.
 * @summary Get all episodes in a folder for playlist building
 */
const getApiStudioFoldersFolderIdEpisodes = (
    folderId: string, options?: AxiosRequestConfig
 ): Promise<AxiosResponse<void>> => {
    return axiosInstance.get(
      `/api/studio/folders/${folderId}/episodes`,options
    );
  }

/**
 * Batch update sort orders.
 * @summary Batch update sort orders.
 */
const postApiStudioReorder = (
    postApiStudioReorderBody: PostApiStudioReorderBody, options?: AxiosRequestConfig
 ): Promise<AxiosResponse<void>> => {
    return axiosInstance.post(
      `/api/studio/reorder`,
      postApiStudioReorderBody,options
    );
  }

/**
 * List all tags.
 * @summary List all tags.
 */
const getApiStudioTags = (
     options?: AxiosRequestConfig
 ): Promise<AxiosResponse<void>> => {
    return axiosInstance.get(
      `/api/studio/tags`,options
    );
  }

/**
 * Create a tag.
 * @summary Create a tag.
 */
const postApiStudioTags = (
    postApiStudioTagsBody: PostApiStudioTagsBody, options?: AxiosRequestConfig
 ): Promise<AxiosResponse<void>> => {
    return axiosInstance.post(
      `/api/studio/tags`,
      postApiStudioTagsBody,options
    );
  }

/**
 * Delete a tag.
 * @summary Delete a tag.
 */
const deleteApiStudioTagsTagId = (
    tagId: string, options?: AxiosRequestConfig
 ): Promise<AxiosResponse<void>> => {
    return axiosInstance.delete(
      `/api/studio/tags/${tagId}`,options
    );
  }

/**
 * Set tags for a source (replaces all existing).
 * @summary Set tags for a source (replaces all existing).
 */
const postApiStudioSourcesSourceIdTags = (
    sourceId: string,
    postApiStudioSourcesSourceIdTagsBody: PostApiStudioSourcesSourceIdTagsBody, options?: AxiosRequestConfig
 ): Promise<AxiosResponse<void>> => {
    return axiosInstance.post(
      `/api/studio/sources/${sourceId}/tags`,
      postApiStudioSourcesSourceIdTagsBody,options
    );
  }

/**
 * Set tags for an episode (replaces all existing).
 * @summary Set tags for an episode (replaces all existing).
 */
const postApiStudioEpisodesEpisodeIdTags = (
    episodeId: string,
    postApiStudioEpisodesEpisodeIdTagsBody: PostApiStudioEpisodesEpisodeIdTagsBody, options?: AxiosRequestConfig
 ): Promise<AxiosResponse<void>> => {
    return axiosInstance.post(
      `/api/studio/episodes/${episodeId}/tags`,
      postApiStudioEpisodesEpisodeIdTagsBody,options
    );
  }

/**
 * Get playback state for an episode.
 * @summary Get playback state for an episode.
 */
const getApiStudioPlaybackEpisodeId = (
    episodeId: string, options?: AxiosRequestConfig
 ): Promise<AxiosResponse<void>> => {
    return axiosInstance.get(
      `/api/studio/playback/${episodeId}`,options
    );
  }

/**
 * Save playback position.
 * @summary Save playback position.
 */
const postApiStudioPlaybackEpisodeId = (
    episodeId: string,
    postApiStudioPlaybackEpisodeIdBody: PostApiStudioPlaybackEpisodeIdBody, options?: AxiosRequestConfig
 ): Promise<AxiosResponse<void>> => {
    return axiosInstance.post(
      `/api/studio/playback/${episodeId}`,
      postApiStudioPlaybackEpisodeIdBody,options
    );
  }

/**
 * Get all settings.
 * @summary Get all settings.
 */
const getApiStudioSettings = (
     options?: AxiosRequestConfig
 ): Promise<AxiosResponse<void>> => {
    return axiosInstance.get(
      `/api/studio/settings`,options
    );
  }

/**
 * Update settings (key-value pairs).
 * @summary Update settings (key-value pairs).
 */
const putApiStudioSettings = (
    putApiStudioSettingsBody: PutApiStudioSettingsBody, options?: AxiosRequestConfig
 ): Promise<AxiosResponse<void>> => {
    return axiosInstance.put(
      `/api/studio/settings`,
      putApiStudioSettingsBody,options
    );
  }

/**
 * Get generation queue status.
 * @summary Get generation queue status.
 */
const getApiStudioGenerationStatus = (
     options?: AxiosRequestConfig
 ): Promise<AxiosResponse<void>> => {
    return axiosInstance.get(
      `/api/studio/generation/status`,options
    );
  }

/**
 * Get the full library tree structure.
 * @summary Get the full library tree structure.
 */
const getApiStudioLibraryTree = (
     options?: AxiosRequestConfig
 ): Promise<AxiosResponse<void>> => {
    return axiosInstance.get(
      `/api/studio/library/tree`,options
    );
  }

/**
 * Preview normalization without saving.
 * @summary Preview normalization without saving.
 */
const postApiStudioPreviewClean = (
    postApiStudioPreviewCleanBody: PostApiStudioPreviewCleanBody, options?: AxiosRequestConfig
 ): Promise<AxiosResponse<void>> => {
    return axiosInstance.post(
      `/api/studio/preview-clean`,
      postApiStudioPreviewCleanBody,options
    );
  }

/**
 * Preview content without importing - for URL and git repos.
 * @summary Preview content without importing - for URL and gi
 */
const postApiStudioPreviewContent = (
    postApiStudioPreviewContentBody: PostApiStudioPreviewContentBody, options?: AxiosRequestConfig
 ): Promise<AxiosResponse<void>> => {
    return axiosInstance.post(
      `/api/studio/preview-content`,
      postApiStudioPreviewContentBody,options
    );
  }

/**
 * Preview chunking without creating an episode.
 * @summary Preview chunking without creating an episode.
 */
const postApiStudioPreviewChunks = (
    postApiStudioPreviewChunksBody: PostApiStudioPreviewChunksBody, options?: AxiosRequestConfig
 ): Promise<AxiosResponse<void>> => {
    return axiosInstance.post(
      `/api/studio/preview-chunks`,
      postApiStudioPreviewChunksBody,options
    );
  }

return {getOpenapiJson,get,getHealth,getV1Voices,postV1AudioSpeech,postApiStudioSources,getApiStudioSources,getApiStudioSourcesSourceId,putApiStudioSourcesSourceId,deleteApiStudioSourcesSourceId,getApiStudioSourcesSourceIdCover,postApiStudioSourcesSourceIdCover,postApiStudioSourcesSourceIdReClean,putApiStudioSourcesSourceIdMove,postApiStudioEpisodes,getApiStudioEpisodes,getApiStudioEpisodesEpisodeId,putApiStudioEpisodesEpisodeId,deleteApiStudioEpisodesEpisodeId,postApiStudioEpisodesEpisodeIdRegenerate,postApiStudioEpisodesEpisodeIdRegenerateWithSettings,postApiStudioUndoUndoId,postApiStudioEpisodesBulkMove,postApiStudioEpisodesBulkDelete,postApiStudioEpisodesEpisodeIdChunksChunkIndexRegenerate,postApiStudioEpisodesEpisodeIdCancel,postApiStudioEpisodesEpisodeIdRetryErrors,getApiStudioEpisodesEpisodeIdAudioChunkIndex,getApiStudioEpisodesEpisodeIdAudioFull,putApiStudioEpisodesEpisodeIdMove,postApiStudioFolders,putApiStudioFoldersFolderId,deleteApiStudioFoldersFolderId,postApiStudioFoldersFolderIdPlaylist,getApiStudioFoldersFolderIdEpisodes,postApiStudioReorder,getApiStudioTags,postApiStudioTags,deleteApiStudioTagsTagId,postApiStudioSourcesSourceIdTags,postApiStudioEpisodesEpisodeIdTags,getApiStudioPlaybackEpisodeId,postApiStudioPlaybackEpisodeId,getApiStudioSettings,putApiStudioSettings,getApiStudioGenerationStatus,getApiStudioLibraryTree,postApiStudioPreviewClean,postApiStudioPreviewContent,postApiStudioPreviewChunks}};
export type GetOpenapiJsonResult = AxiosResponse<void>
export type GetResult = AxiosResponse<void>
export type GetHealthResult = AxiosResponse<void>
export type GetV1VoicesResult = AxiosResponse<void>
export type PostV1AudioSpeechResult = AxiosResponse<void>
export type PostApiStudioSourcesResult = AxiosResponse<void>
export type GetApiStudioSourcesResult = AxiosResponse<void>
export type GetApiStudioSourcesSourceIdResult = AxiosResponse<void>
export type PutApiStudioSourcesSourceIdResult = AxiosResponse<void>
export type DeleteApiStudioSourcesSourceIdResult = AxiosResponse<void>
export type GetApiStudioSourcesSourceIdCoverResult = AxiosResponse<void>
export type PostApiStudioSourcesSourceIdCoverResult = AxiosResponse<void>
export type PostApiStudioSourcesSourceIdReCleanResult = AxiosResponse<void>
export type PutApiStudioSourcesSourceIdMoveResult = AxiosResponse<void>
export type PostApiStudioEpisodesResult = AxiosResponse<void>
export type GetApiStudioEpisodesResult = AxiosResponse<void>
export type GetApiStudioEpisodesEpisodeIdResult = AxiosResponse<void>
export type PutApiStudioEpisodesEpisodeIdResult = AxiosResponse<void>
export type DeleteApiStudioEpisodesEpisodeIdResult = AxiosResponse<void>
export type PostApiStudioEpisodesEpisodeIdRegenerateResult = AxiosResponse<void>
export type PostApiStudioEpisodesEpisodeIdRegenerateWithSettingsResult = AxiosResponse<void>
export type PostApiStudioUndoUndoIdResult = AxiosResponse<void>
export type PostApiStudioEpisodesBulkMoveResult = AxiosResponse<void>
export type PostApiStudioEpisodesBulkDeleteResult = AxiosResponse<void>
export type PostApiStudioEpisodesEpisodeIdChunksChunkIndexRegenerateResult = AxiosResponse<void>
export type PostApiStudioEpisodesEpisodeIdCancelResult = AxiosResponse<void>
export type PostApiStudioEpisodesEpisodeIdRetryErrorsResult = AxiosResponse<void>
export type GetApiStudioEpisodesEpisodeIdAudioChunkIndexResult = AxiosResponse<void>
export type GetApiStudioEpisodesEpisodeIdAudioFullResult = AxiosResponse<void>
export type PutApiStudioEpisodesEpisodeIdMoveResult = AxiosResponse<void>
export type PostApiStudioFoldersResult = AxiosResponse<void>
export type PutApiStudioFoldersFolderIdResult = AxiosResponse<void>
export type DeleteApiStudioFoldersFolderIdResult = AxiosResponse<void>
export type PostApiStudioFoldersFolderIdPlaylistResult = AxiosResponse<void>
export type GetApiStudioFoldersFolderIdEpisodesResult = AxiosResponse<void>
export type PostApiStudioReorderResult = AxiosResponse<void>
export type GetApiStudioTagsResult = AxiosResponse<void>
export type PostApiStudioTagsResult = AxiosResponse<void>
export type DeleteApiStudioTagsTagIdResult = AxiosResponse<void>
export type PostApiStudioSourcesSourceIdTagsResult = AxiosResponse<void>
export type PostApiStudioEpisodesEpisodeIdTagsResult = AxiosResponse<void>
export type GetApiStudioPlaybackEpisodeIdResult = AxiosResponse<void>
export type PostApiStudioPlaybackEpisodeIdResult = AxiosResponse<void>
export type GetApiStudioSettingsResult = AxiosResponse<void>
export type PutApiStudioSettingsResult = AxiosResponse<void>
export type GetApiStudioGenerationStatusResult = AxiosResponse<void>
export type GetApiStudioLibraryTreeResult = AxiosResponse<void>
export type PostApiStudioPreviewCleanResult = AxiosResponse<void>
export type PostApiStudioPreviewContentResult = AxiosResponse<void>
export type PostApiStudioPreviewChunksResult = AxiosResponse<void>
