/**
 * Generated by orval v8.4.2 🍺
 * Do not edit manually.
 * OpenVox API
 * OpenAPI spec version: 1.0.0
 */
import { customInstance } from './custom-instance';
import type { BodyType } from './custom-instance';
export interface SpeechGenerationBody {
  /** Text to synthesize */
  input: string;
  /** Voice ID or path */
  voice?: string;
  /** Model name (ignored, for OpenAI compatibility) */
  model?: string;
  /** Audio format: mp3, wav, pcm, opus */
  response_format?: string;
  /** Enable streaming response */
  stream?: boolean;
}

export interface CleaningSettings {
  /** How to handle code blocks: skip, read, summarize */
  code_block_rule?: string;
  remove_non_text?: boolean;
  handle_tables?: boolean;
  speak_urls?: boolean;
  expand_abbreviations?: boolean;
  preserve_parentheses?: boolean;
  preserve_structure?: boolean;
  paragraph_spacing?: number;
  section_spacing?: number;
  list_item_spacing?: number;
}

export interface UrlSettings {
  /** Use Jina Reader for URL extraction */
  use_jina?: boolean;
  /** Fall back to Jina if other methods fail */
  jina_fallback?: boolean;
}

export interface CreateSourceJsonBody {
  /** Raw text to import */
  text?: string;
  /** Source title */
  title?: string;
  /** URL to import content from */
  url?: string;
  /** Git repository URL to import */
  git_url?: string;
  /** Subdirectory path within the git repo */
  git_subpath?: string;
  /** Override cleaning options */
  cleaning_settings?: CleaningSettings;
  /** URL extraction settings */
  url_settings?: UrlSettings;
}

export interface CreateSourceFileBody {
  /** File to upload (.md, .txt) */
  file?: string;
}

export interface SourceCoverUploadBody {
  /** Cover art image file */
  cover?: string;
}

export interface UpdateSourceBody {
  title?: string;
  cleaned_text?: string;
}

export interface ReCleanSourceBody {
  code_block_rule?: string;
  remove_non_text?: boolean;
  handle_tables?: boolean;
  speak_urls?: boolean;
  expand_abbreviations?: boolean;
  preserve_parentheses?: boolean;
}

export interface MoveToFolderBody {
  /**
   * Target folder ID, or null for root
   * @nullable
   */
  folder_id?: string | null;
}

export interface CreateEpisodeBody {
  source_id: string;
  voice_id?: string;
  output_format?: string;
  /** paragraph, sentence, heading, or fixed */
  chunk_strategy?: string;
  chunk_max_length?: number;
  code_block_rule?: string;
  /** none, light, normal, heavy */
  breathing_intensity?: string;
  title?: string;
}

export interface UpdateEpisodeBody {
  title?: string;
}

export interface RegenerateWithSettingsBody {
  voice_id?: string;
  output_format?: string;
  chunk_strategy?: string;
  chunk_max_length?: number;
  code_block_rule?: string;
  breathing_intensity?: string;
}

export interface BulkMoveEpisodesBody {
  episode_ids: string[];
  /** @nullable */
  folder_id?: string | null;
}

export interface BulkDeleteEpisodesBody {
  episode_ids: string[];
}

export interface CreateFolderBody {
  name?: string;
  /** @nullable */
  parent_id?: string | null;
  sort_order?: number;
}

export interface UpdateFolderBody {
  name?: string;
  /** @nullable */
  parent_id?: string | null;
  sort_order?: number;
}

export interface ReorderItem {
  type?: string;
  id: string;
  sort_order: number;
}

export interface ReorderBody {
  items?: ReorderItem[];
}

export interface CreateTagBody {
  name: string;
}

export interface SetTagsBody {
  /** Tag IDs to assign (replaces existing) */
  tag_ids?: string[];
}

export interface SavePlaybackBody {
  current_chunk_index?: number;
  position_secs?: number;
  percent_listened?: number;
}

export interface UpdateSettingsBody { [key: string]: unknown }

export interface PreviewCleanBody {
  text: string;
  code_block_rule?: string;
}

export interface PreviewContentBody {
  /** Content type: url or git */
  type: string;
  url?: string;
  subpath?: string;
}

export interface PreviewChunksBody {
  text: string;
  strategy?: string;
  max_chars?: number;
}

type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];


  export const getOpenVoxAPI = () => {
/**
 * Serve OpenAPI spec for Orval client generation.
 * @summary Serve OpenAPI spec for Orval client generation.
 */
const getOpenapiJson = (
    
 options?: SecondParameter<typeof customInstance<void>>,) => {
      return customInstance<void>(
      {url: `/openapi.json`, method: 'GET'
    },
      options);
    }
  
/**
 * Serve the web interface.
 * @summary Serve the web interface.
 */
const get = (
    
 options?: SecondParameter<typeof customInstance<void>>,) => {
      return customInstance<void>(
      {url: `/`, method: 'GET'
    },
      options);
    }
  
/**
 * Health check endpoint for container orchestration.

Returns service status and basic model info.
 * @summary Health check endpoint for container orchestration.
 */
const getHealth = (
    
 options?: SecondParameter<typeof customInstance<void>>,) => {
      return customInstance<void>(
      {url: `/health`, method: 'GET'
    },
      options);
    }
  
/**
 * List available voices.

Returns OpenAI-compatible voice list format.
 * @summary List available voices.
 */
const getV1Voices = (
    
 options?: SecondParameter<typeof customInstance<void>>,) => {
      return customInstance<void>(
      {url: `/v1/voices`, method: 'GET'
    },
      options);
    }
  
/**
 * OpenAI-compatible speech generation endpoint.

Request body:
    model: string (ignored, for compatibility)
    input: string (required) - Text to synthesize
    voice: string (optional) - Voice ID or path
    response_format: string (optional) - Audio format
    stream: boolean (optional) - Enable streaming

Returns:
    Audio file or streaming audio response
 * @summary OpenAI-compatible speech generation endpoint.
 */
const postV1AudioSpeech = (
    speechGenerationBody: BodyType<SpeechGenerationBody>,
 options?: SecondParameter<typeof customInstance<void>>,) => {
      return customInstance<void>(
      {url: `/v1/audio/speech`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: speechGenerationBody
    },
      options);
    }
  
/**
 * Upload file, submit URL, paste text, or import git repository.
 * @summary Upload file, submit URL, paste text, or import git
 */
const postApiStudioSources = (
    postApiStudioSourcesBody: BodyType<CreateSourceJsonBody | CreateSourceFileBody>| CreateSourceFileBody,
 options?: SecondParameter<typeof customInstance<void>>,) => {
      return customInstance<void>(
      {url: `/api/studio/sources`, method: 'POST',
      data: postApiStudioSourcesBody
    },
      options);
    }
  
/**
 * List all sources.
 * @summary List all sources.
 */
const getApiStudioSources = (
    
 options?: SecondParameter<typeof customInstance<void>>,) => {
      return customInstance<void>(
      {url: `/api/studio/sources`, method: 'GET'
    },
      options);
    }
  
/**
 * Get a source with cleaned text.
 * @summary Get a source with cleaned text.
 */
const getApiStudioSourcesSourceId = (
    sourceId: string,
 options?: SecondParameter<typeof customInstance<void>>,) => {
      return customInstance<void>(
      {url: `/api/studio/sources/${sourceId}`, method: 'GET'
    },
      options);
    }
  
/**
 * Update source title or cleaned_text.
 * @summary Update source title or cleaned_text.
 */
const putApiStudioSourcesSourceId = (
    sourceId: string,
    updateSourceBody: BodyType<UpdateSourceBody>,
 options?: SecondParameter<typeof customInstance<void>>,) => {
      return customInstance<void>(
      {url: `/api/studio/sources/${sourceId}`, method: 'PUT',
      headers: {'Content-Type': 'application/json', },
      data: updateSourceBody
    },
      options);
    }
  
/**
 * Delete source and associated episodes/audio.
 * @summary Delete source and associated episodes/audio.
 */
const deleteApiStudioSourcesSourceId = (
    sourceId: string,
 options?: SecondParameter<typeof customInstance<void>>,) => {
      return customInstance<void>(
      {url: `/api/studio/sources/${sourceId}`, method: 'DELETE'
    },
      options);
    }
  
/**
 * Get cover art for a source.
 * @summary Get cover art for a source.
 */
const getApiStudioSourcesSourceIdCover = (
    sourceId: string,
 options?: SecondParameter<typeof customInstance<void>>,) => {
      return customInstance<void>(
      {url: `/api/studio/sources/${sourceId}/cover`, method: 'GET'
    },
      options);
    }
  
/**
 * Upload cover art for a source.
 * @summary Upload cover art for a source.
 */
const postApiStudioSourcesSourceIdCover = (
    sourceId: string,
    sourceCoverUploadBody: BodyType<SourceCoverUploadBody>,
 options?: SecondParameter<typeof customInstance<void>>,) => {const formData = new FormData();
if(sourceCoverUploadBody.cover !== undefined) {
 formData.append(`cover`, sourceCoverUploadBody.cover);
 }

      return customInstance<void>(
      {url: `/api/studio/sources/${sourceId}/cover`, method: 'POST',
       data: formData
    },
      options);
    }
  
/**
 * Re-run normalizer on a source with different options.
 * @summary Re-run normalizer on a source with different optio
 */
const postApiStudioSourcesSourceIdReClean = (
    sourceId: string,
    reCleanSourceBody: BodyType<ReCleanSourceBody>,
 options?: SecondParameter<typeof customInstance<void>>,) => {
      return customInstance<void>(
      {url: `/api/studio/sources/${sourceId}/re-clean`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: reCleanSourceBody
    },
      options);
    }
  
/**
 * Move a source to a folder.
 * @summary Move a source to a folder.
 */
const putApiStudioSourcesSourceIdMove = (
    sourceId: string,
    moveToFolderBody: BodyType<MoveToFolderBody>,
 options?: SecondParameter<typeof customInstance<void>>,) => {
      return customInstance<void>(
      {url: `/api/studio/sources/${sourceId}/move`, method: 'PUT',
      headers: {'Content-Type': 'application/json', },
      data: moveToFolderBody
    },
      options);
    }
  
/**
 * Create an episode — chunk text and enqueue generation.
 * @summary Create an episode — chunk text and enqueue generat
 */
const postApiStudioEpisodes = (
    createEpisodeBody: BodyType<CreateEpisodeBody>,
 options?: SecondParameter<typeof customInstance<void>>,) => {
      return customInstance<void>(
      {url: `/api/studio/episodes`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: createEpisodeBody
    },
      options);
    }
  
/**
 * List all episodes.
 * @summary List all episodes.
 */
const getApiStudioEpisodes = (
    
 options?: SecondParameter<typeof customInstance<void>>,) => {
      return customInstance<void>(
      {url: `/api/studio/episodes`, method: 'GET'
    },
      options);
    }
  
/**
 * Get episode with its chunks.
 * @summary Get episode with its chunks.
 */
const getApiStudioEpisodesEpisodeId = (
    episodeId: string,
 options?: SecondParameter<typeof customInstance<void>>,) => {
      return customInstance<void>(
      {url: `/api/studio/episodes/${episodeId}`, method: 'GET'
    },
      options);
    }
  
/**
 * Update episode metadata.
 * @summary Update episode metadata.
 */
const putApiStudioEpisodesEpisodeId = (
    episodeId: string,
    updateEpisodeBody: BodyType<UpdateEpisodeBody>,
 options?: SecondParameter<typeof customInstance<void>>,) => {
      return customInstance<void>(
      {url: `/api/studio/episodes/${episodeId}`, method: 'PUT',
      headers: {'Content-Type': 'application/json', },
      data: updateEpisodeBody
    },
      options);
    }
  
/**
 * Delete episode and audio files.
 * @summary Delete episode and audio files.
 */
const deleteApiStudioEpisodesEpisodeId = (
    episodeId: string,
 options?: SecondParameter<typeof customInstance<void>>,) => {
      return customInstance<void>(
      {url: `/api/studio/episodes/${episodeId}`, method: 'DELETE'
    },
      options);
    }
  
/**
 * Re-generate all chunks for an episode.
 * @summary Re-generate all chunks for an episode.
 */
const postApiStudioEpisodesEpisodeIdRegenerate = (
    episodeId: string,
 options?: SecondParameter<typeof customInstance<void>>,) => {
      return customInstance<void>(
      {url: `/api/studio/episodes/${episodeId}/regenerate`, method: 'POST'
    },
      options);
    }
  
/**
 * Re-generate episode with new settings, with undo support.
 * @summary Re-generate episode with new settings, with undo s
 */
const postApiStudioEpisodesEpisodeIdRegenerateWithSettings = (
    episodeId: string,
    regenerateWithSettingsBody: BodyType<RegenerateWithSettingsBody>,
 options?: SecondParameter<typeof customInstance<void>>,) => {
      return customInstance<void>(
      {url: `/api/studio/episodes/${episodeId}/regenerate-with-settings`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: regenerateWithSettingsBody
    },
      options);
    }
  
/**
 * Undo an episode regeneration within the grace period.
 * @summary Undo an episode regeneration within the grace peri
 */
const postApiStudioUndoUndoId = (
    undoId: string,
 options?: SecondParameter<typeof customInstance<void>>,) => {
      return customInstance<void>(
      {url: `/api/studio/undo/${undoId}`, method: 'POST'
    },
      options);
    }
  
/**
 * Move multiple episodes to a folder.
 * @summary Move multiple episodes to a folder.
 */
const postApiStudioEpisodesBulkMove = (
    bulkMoveEpisodesBody: BodyType<BulkMoveEpisodesBody>,
 options?: SecondParameter<typeof customInstance<void>>,) => {
      return customInstance<void>(
      {url: `/api/studio/episodes/bulk-move`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: bulkMoveEpisodesBody
    },
      options);
    }
  
/**
 * Delete multiple episodes.
 * @summary Delete multiple episodes.
 */
const postApiStudioEpisodesBulkDelete = (
    bulkDeleteEpisodesBody: BodyType<BulkDeleteEpisodesBody>,
 options?: SecondParameter<typeof customInstance<void>>,) => {
      return customInstance<void>(
      {url: `/api/studio/episodes/bulk-delete`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: bulkDeleteEpisodesBody
    },
      options);
    }
  
/**
 * Regenerate a single chunk.
 * @summary Regenerate a single chunk.
 */
const postApiStudioEpisodesEpisodeIdChunksChunkIndexRegenerate = (
    episodeId: string,
    chunkIndex: number,
 options?: SecondParameter<typeof customInstance<void>>,) => {
      return customInstance<void>(
      {url: `/api/studio/episodes/${episodeId}/chunks/${chunkIndex}/regenerate`, method: 'POST'
    },
      options);
    }
  
/**
 * Cancel a generating episode and reset error chunks to pending.
 * @summary Cancel a generating episode and reset error chunks
 */
const postApiStudioEpisodesEpisodeIdCancel = (
    episodeId: string,
 options?: SecondParameter<typeof customInstance<void>>,) => {
      return customInstance<void>(
      {url: `/api/studio/episodes/${episodeId}/cancel`, method: 'POST'
    },
      options);
    }
  
/**
 * Retry all error chunks for an episode.
 * @summary Retry all error chunks for an episode.
 */
const postApiStudioEpisodesEpisodeIdRetryErrors = (
    episodeId: string,
 options?: SecondParameter<typeof customInstance<void>>,) => {
      return customInstance<void>(
      {url: `/api/studio/episodes/${episodeId}/retry-errors`, method: 'POST'
    },
      options);
    }
  
/**
 * Serve a chunk's audio file.
 * @summary Serve a chunk's audio file.
 */
const getApiStudioEpisodesEpisodeIdAudioChunkIndex = (
    episodeId: string,
    chunkIndex: number,
 options?: SecondParameter<typeof customInstance<void>>,) => {
      return customInstance<void>(
      {url: `/api/studio/episodes/${episodeId}/audio/${chunkIndex}`, method: 'GET'
    },
      options);
    }
  
/**
 * Serve merged full episode audio.
 * @summary Serve merged full episode audio.
 */
const getApiStudioEpisodesEpisodeIdAudioFull = (
    episodeId: string,
 options?: SecondParameter<typeof customInstance<void>>,) => {
      return customInstance<void>(
      {url: `/api/studio/episodes/${episodeId}/audio/full`, method: 'GET'
    },
      options);
    }
  
/**
 * Move an episode to a folder.
 * @summary Move an episode to a folder.
 */
const putApiStudioEpisodesEpisodeIdMove = (
    episodeId: string,
    moveToFolderBody: BodyType<MoveToFolderBody>,
 options?: SecondParameter<typeof customInstance<void>>,) => {
      return customInstance<void>(
      {url: `/api/studio/episodes/${episodeId}/move`, method: 'PUT',
      headers: {'Content-Type': 'application/json', },
      data: moveToFolderBody
    },
      options);
    }
  
/**
 * Create a new folder.
 * @summary Create a new folder.
 */
const postApiStudioFolders = (
    createFolderBody: BodyType<CreateFolderBody>,
 options?: SecondParameter<typeof customInstance<void>>,) => {
      return customInstance<void>(
      {url: `/api/studio/folders`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: createFolderBody
    },
      options);
    }
  
/**
 * Rename or move a folder.
 * @summary Rename or move a folder.
 */
const putApiStudioFoldersFolderId = (
    folderId: string,
    updateFolderBody: BodyType<UpdateFolderBody>,
 options?: SecondParameter<typeof customInstance<void>>,) => {
      return customInstance<void>(
      {url: `/api/studio/folders/${folderId}`, method: 'PUT',
      headers: {'Content-Type': 'application/json', },
      data: updateFolderBody
    },
      options);
    }
  
/**
 * Delete a folder and all its contents (episodes audio files are deleted).
 * @summary Delete a folder and all its contents (episodes aud
 */
const deleteApiStudioFoldersFolderId = (
    folderId: string,
 options?: SecondParameter<typeof customInstance<void>>,) => {
      return customInstance<void>(
      {url: `/api/studio/folders/${folderId}`, method: 'DELETE'
    },
      options);
    }
  
/**
 * Start playing all episodes in a folder as a playlist.
 * @summary Start playing all episodes in a folder as a playli
 */
const postApiStudioFoldersFolderIdPlaylist = (
    folderId: string,
 options?: SecondParameter<typeof customInstance<void>>,) => {
      return customInstance<void>(
      {url: `/api/studio/folders/${folderId}/playlist`, method: 'POST'
    },
      options);
    }
  
/**
 * Get all episodes in a folder for playlist building.
 * @summary Get all episodes in a folder for playlist building
 */
const getApiStudioFoldersFolderIdEpisodes = (
    folderId: string,
 options?: SecondParameter<typeof customInstance<void>>,) => {
      return customInstance<void>(
      {url: `/api/studio/folders/${folderId}/episodes`, method: 'GET'
    },
      options);
    }
  
/**
 * Batch update sort orders.
 * @summary Batch update sort orders.
 */
const postApiStudioReorder = (
    reorderBody: BodyType<ReorderBody>,
 options?: SecondParameter<typeof customInstance<void>>,) => {
      return customInstance<void>(
      {url: `/api/studio/reorder`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: reorderBody
    },
      options);
    }
  
/**
 * List all tags.
 * @summary List all tags.
 */
const getApiStudioTags = (
    
 options?: SecondParameter<typeof customInstance<void>>,) => {
      return customInstance<void>(
      {url: `/api/studio/tags`, method: 'GET'
    },
      options);
    }
  
/**
 * Create a tag.
 * @summary Create a tag.
 */
const postApiStudioTags = (
    createTagBody: BodyType<CreateTagBody>,
 options?: SecondParameter<typeof customInstance<void>>,) => {
      return customInstance<void>(
      {url: `/api/studio/tags`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: createTagBody
    },
      options);
    }
  
/**
 * Delete a tag.
 * @summary Delete a tag.
 */
const deleteApiStudioTagsTagId = (
    tagId: string,
 options?: SecondParameter<typeof customInstance<void>>,) => {
      return customInstance<void>(
      {url: `/api/studio/tags/${tagId}`, method: 'DELETE'
    },
      options);
    }
  
/**
 * Set tags for a source (replaces all existing).
 * @summary Set tags for a source (replaces all existing).
 */
const postApiStudioSourcesSourceIdTags = (
    sourceId: string,
    setTagsBody: BodyType<SetTagsBody>,
 options?: SecondParameter<typeof customInstance<void>>,) => {
      return customInstance<void>(
      {url: `/api/studio/sources/${sourceId}/tags`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: setTagsBody
    },
      options);
    }
  
/**
 * Set tags for an episode (replaces all existing).
 * @summary Set tags for an episode (replaces all existing).
 */
const postApiStudioEpisodesEpisodeIdTags = (
    episodeId: string,
    setTagsBody: BodyType<SetTagsBody>,
 options?: SecondParameter<typeof customInstance<void>>,) => {
      return customInstance<void>(
      {url: `/api/studio/episodes/${episodeId}/tags`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: setTagsBody
    },
      options);
    }
  
/**
 * Get playback state for an episode.
 * @summary Get playback state for an episode.
 */
const getApiStudioPlaybackEpisodeId = (
    episodeId: string,
 options?: SecondParameter<typeof customInstance<void>>,) => {
      return customInstance<void>(
      {url: `/api/studio/playback/${episodeId}`, method: 'GET'
    },
      options);
    }
  
/**
 * Save playback position.
 * @summary Save playback position.
 */
const postApiStudioPlaybackEpisodeId = (
    episodeId: string,
    savePlaybackBody: BodyType<SavePlaybackBody>,
 options?: SecondParameter<typeof customInstance<void>>,) => {
      return customInstance<void>(
      {url: `/api/studio/playback/${episodeId}`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: savePlaybackBody
    },
      options);
    }
  
/**
 * Get all settings.
 * @summary Get all settings.
 */
const getApiStudioSettings = (
    
 options?: SecondParameter<typeof customInstance<void>>,) => {
      return customInstance<void>(
      {url: `/api/studio/settings`, method: 'GET'
    },
      options);
    }
  
/**
 * Update settings (key-value pairs).
 * @summary Update settings (key-value pairs).
 */
const putApiStudioSettings = (
    updateSettingsBody: BodyType<UpdateSettingsBody>,
 options?: SecondParameter<typeof customInstance<void>>,) => {
      return customInstance<void>(
      {url: `/api/studio/settings`, method: 'PUT',
      headers: {'Content-Type': 'application/json', },
      data: updateSettingsBody
    },
      options);
    }
  
/**
 * Get generation queue status.
 * @summary Get generation queue status.
 */
const getApiStudioGenerationStatus = (
    
 options?: SecondParameter<typeof customInstance<void>>,) => {
      return customInstance<void>(
      {url: `/api/studio/generation/status`, method: 'GET'
    },
      options);
    }
  
/**
 * Get the full library tree structure.
 * @summary Get the full library tree structure.
 */
const getApiStudioLibraryTree = (
    
 options?: SecondParameter<typeof customInstance<void>>,) => {
      return customInstance<void>(
      {url: `/api/studio/library/tree`, method: 'GET'
    },
      options);
    }
  
/**
 * Preview normalization without saving.
 * @summary Preview normalization without saving.
 */
const postApiStudioPreviewClean = (
    previewCleanBody: BodyType<PreviewCleanBody>,
 options?: SecondParameter<typeof customInstance<void>>,) => {
      return customInstance<void>(
      {url: `/api/studio/preview-clean`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: previewCleanBody
    },
      options);
    }
  
/**
 * Preview content without importing - for URL and git repos.
 * @summary Preview content without importing - for URL and gi
 */
const postApiStudioPreviewContent = (
    previewContentBody: BodyType<PreviewContentBody>,
 options?: SecondParameter<typeof customInstance<void>>,) => {
      return customInstance<void>(
      {url: `/api/studio/preview-content`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: previewContentBody
    },
      options);
    }
  
/**
 * Preview chunking without creating an episode.
 * @summary Preview chunking without creating an episode.
 */
const postApiStudioPreviewChunks = (
    previewChunksBody: BodyType<PreviewChunksBody>,
 options?: SecondParameter<typeof customInstance<void>>,) => {
      return customInstance<void>(
      {url: `/api/studio/preview-chunks`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: previewChunksBody
    },
      options);
    }
  
return {getOpenapiJson,get,getHealth,getV1Voices,postV1AudioSpeech,postApiStudioSources,getApiStudioSources,getApiStudioSourcesSourceId,putApiStudioSourcesSourceId,deleteApiStudioSourcesSourceId,getApiStudioSourcesSourceIdCover,postApiStudioSourcesSourceIdCover,postApiStudioSourcesSourceIdReClean,putApiStudioSourcesSourceIdMove,postApiStudioEpisodes,getApiStudioEpisodes,getApiStudioEpisodesEpisodeId,putApiStudioEpisodesEpisodeId,deleteApiStudioEpisodesEpisodeId,postApiStudioEpisodesEpisodeIdRegenerate,postApiStudioEpisodesEpisodeIdRegenerateWithSettings,postApiStudioUndoUndoId,postApiStudioEpisodesBulkMove,postApiStudioEpisodesBulkDelete,postApiStudioEpisodesEpisodeIdChunksChunkIndexRegenerate,postApiStudioEpisodesEpisodeIdCancel,postApiStudioEpisodesEpisodeIdRetryErrors,getApiStudioEpisodesEpisodeIdAudioChunkIndex,getApiStudioEpisodesEpisodeIdAudioFull,putApiStudioEpisodesEpisodeIdMove,postApiStudioFolders,putApiStudioFoldersFolderId,deleteApiStudioFoldersFolderId,postApiStudioFoldersFolderIdPlaylist,getApiStudioFoldersFolderIdEpisodes,postApiStudioReorder,getApiStudioTags,postApiStudioTags,deleteApiStudioTagsTagId,postApiStudioSourcesSourceIdTags,postApiStudioEpisodesEpisodeIdTags,getApiStudioPlaybackEpisodeId,postApiStudioPlaybackEpisodeId,getApiStudioSettings,putApiStudioSettings,getApiStudioGenerationStatus,getApiStudioLibraryTree,postApiStudioPreviewClean,postApiStudioPreviewContent,postApiStudioPreviewChunks}};
export type GetOpenapiJsonResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getOpenVoxAPI>['getOpenapiJson']>>>
export type GetResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getOpenVoxAPI>['get']>>>
export type GetHealthResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getOpenVoxAPI>['getHealth']>>>
export type GetV1VoicesResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getOpenVoxAPI>['getV1Voices']>>>
export type PostV1AudioSpeechResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getOpenVoxAPI>['postV1AudioSpeech']>>>
export type PostApiStudioSourcesResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getOpenVoxAPI>['postApiStudioSources']>>>
export type GetApiStudioSourcesResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getOpenVoxAPI>['getApiStudioSources']>>>
export type GetApiStudioSourcesSourceIdResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getOpenVoxAPI>['getApiStudioSourcesSourceId']>>>
export type PutApiStudioSourcesSourceIdResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getOpenVoxAPI>['putApiStudioSourcesSourceId']>>>
export type DeleteApiStudioSourcesSourceIdResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getOpenVoxAPI>['deleteApiStudioSourcesSourceId']>>>
export type GetApiStudioSourcesSourceIdCoverResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getOpenVoxAPI>['getApiStudioSourcesSourceIdCover']>>>
export type PostApiStudioSourcesSourceIdCoverResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getOpenVoxAPI>['postApiStudioSourcesSourceIdCover']>>>
export type PostApiStudioSourcesSourceIdReCleanResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getOpenVoxAPI>['postApiStudioSourcesSourceIdReClean']>>>
export type PutApiStudioSourcesSourceIdMoveResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getOpenVoxAPI>['putApiStudioSourcesSourceIdMove']>>>
export type PostApiStudioEpisodesResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getOpenVoxAPI>['postApiStudioEpisodes']>>>
export type GetApiStudioEpisodesResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getOpenVoxAPI>['getApiStudioEpisodes']>>>
export type GetApiStudioEpisodesEpisodeIdResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getOpenVoxAPI>['getApiStudioEpisodesEpisodeId']>>>
export type PutApiStudioEpisodesEpisodeIdResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getOpenVoxAPI>['putApiStudioEpisodesEpisodeId']>>>
export type DeleteApiStudioEpisodesEpisodeIdResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getOpenVoxAPI>['deleteApiStudioEpisodesEpisodeId']>>>
export type PostApiStudioEpisodesEpisodeIdRegenerateResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getOpenVoxAPI>['postApiStudioEpisodesEpisodeIdRegenerate']>>>
export type PostApiStudioEpisodesEpisodeIdRegenerateWithSettingsResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getOpenVoxAPI>['postApiStudioEpisodesEpisodeIdRegenerateWithSettings']>>>
export type PostApiStudioUndoUndoIdResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getOpenVoxAPI>['postApiStudioUndoUndoId']>>>
export type PostApiStudioEpisodesBulkMoveResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getOpenVoxAPI>['postApiStudioEpisodesBulkMove']>>>
export type PostApiStudioEpisodesBulkDeleteResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getOpenVoxAPI>['postApiStudioEpisodesBulkDelete']>>>
export type PostApiStudioEpisodesEpisodeIdChunksChunkIndexRegenerateResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getOpenVoxAPI>['postApiStudioEpisodesEpisodeIdChunksChunkIndexRegenerate']>>>
export type PostApiStudioEpisodesEpisodeIdCancelResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getOpenVoxAPI>['postApiStudioEpisodesEpisodeIdCancel']>>>
export type PostApiStudioEpisodesEpisodeIdRetryErrorsResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getOpenVoxAPI>['postApiStudioEpisodesEpisodeIdRetryErrors']>>>
export type GetApiStudioEpisodesEpisodeIdAudioChunkIndexResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getOpenVoxAPI>['getApiStudioEpisodesEpisodeIdAudioChunkIndex']>>>
export type GetApiStudioEpisodesEpisodeIdAudioFullResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getOpenVoxAPI>['getApiStudioEpisodesEpisodeIdAudioFull']>>>
export type PutApiStudioEpisodesEpisodeIdMoveResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getOpenVoxAPI>['putApiStudioEpisodesEpisodeIdMove']>>>
export type PostApiStudioFoldersResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getOpenVoxAPI>['postApiStudioFolders']>>>
export type PutApiStudioFoldersFolderIdResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getOpenVoxAPI>['putApiStudioFoldersFolderId']>>>
export type DeleteApiStudioFoldersFolderIdResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getOpenVoxAPI>['deleteApiStudioFoldersFolderId']>>>
export type PostApiStudioFoldersFolderIdPlaylistResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getOpenVoxAPI>['postApiStudioFoldersFolderIdPlaylist']>>>
export type GetApiStudioFoldersFolderIdEpisodesResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getOpenVoxAPI>['getApiStudioFoldersFolderIdEpisodes']>>>
export type PostApiStudioReorderResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getOpenVoxAPI>['postApiStudioReorder']>>>
export type GetApiStudioTagsResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getOpenVoxAPI>['getApiStudioTags']>>>
export type PostApiStudioTagsResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getOpenVoxAPI>['postApiStudioTags']>>>
export type DeleteApiStudioTagsTagIdResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getOpenVoxAPI>['deleteApiStudioTagsTagId']>>>
export type PostApiStudioSourcesSourceIdTagsResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getOpenVoxAPI>['postApiStudioSourcesSourceIdTags']>>>
export type PostApiStudioEpisodesEpisodeIdTagsResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getOpenVoxAPI>['postApiStudioEpisodesEpisodeIdTags']>>>
export type GetApiStudioPlaybackEpisodeIdResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getOpenVoxAPI>['getApiStudioPlaybackEpisodeId']>>>
export type PostApiStudioPlaybackEpisodeIdResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getOpenVoxAPI>['postApiStudioPlaybackEpisodeId']>>>
export type GetApiStudioSettingsResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getOpenVoxAPI>['getApiStudioSettings']>>>
export type PutApiStudioSettingsResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getOpenVoxAPI>['putApiStudioSettings']>>>
export type GetApiStudioGenerationStatusResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getOpenVoxAPI>['getApiStudioGenerationStatus']>>>
export type GetApiStudioLibraryTreeResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getOpenVoxAPI>['getApiStudioLibraryTree']>>>
export type PostApiStudioPreviewCleanResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getOpenVoxAPI>['postApiStudioPreviewClean']>>>
export type PostApiStudioPreviewContentResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getOpenVoxAPI>['postApiStudioPreviewContent']>>>
export type PostApiStudioPreviewChunksResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getOpenVoxAPI>['postApiStudioPreviewChunks']>>>
